# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'torpydo:$(build.buildId)'

steps:
- script: docker login -u $(dockerId) -p $(pswd) $(repo)
- script: docker build -f DockerfileBuild -t $(repo)/$(dockerId)/$(imageName) .
  displayName: 'docker build'
- script: docker run -v ${PWD}:/torpydo $(repo)/$(dockerId)/$(imageName) nosetests --exe --with-xunit 
  displayName: 'Run unit tests'
- script: docker run -v ${PWD}:/torpydo $(repo)/$(dockerId)/$(imageName) behave --junit 
  displayName: 'Run behave tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'
    testResultsFormat: JUnit
  displayName: 'Publish Test Results'
- script: docker push $(repo)/$(dockerId)/$(imageName)
  displayName: 'docker push'